"""
build-icons.py — self-host a SUBSET of Bootstrap Icons.

WHY
---
diagnose-fcp.mjs measured first paint tracking the slowest render-blocking
stylesheet in <head>, and the worst offender across runs was the
bootstrap-icons CSS from jsDelivr (182 ms best case, 1086 ms worst). It is
~100 KB of CSS declaring ~2000 icons, of which this page uses 43, and it is
fetched over a third-party connection that the site cannot control.

So: parse the icons actually referenced in index.html, subset the WOFF2 to
just those glyphs with fonttools, and emit a small local CSS file. The
third-party request disappears and the remaining bytes are served from the
same origin as the document.

Idempotent: safe to re-run. Requires network on first run (downloads the
upstream font + CSS into a cache dir), then works offline.

Run:  python build-icons.py
"""

from __future__ import annotations

import io
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).parent
HTML = ROOT / "index.html"
CSS_SRC = ROOT / "assets" / "css"
OUT_CSS = CSS_SRC / "00-icons.css"
FONT_DIR = ROOT / "assets" / "fonts"
CACHE = ROOT / ".cache"

VER = "1.11.3"
BASE = f"https://cdn.jsdelivr.net/npm/bootstrap-icons@{VER}/font"
UP_CSS = f"{BASE}/bootstrap-icons.min.css"
UP_WOFF2 = f"{BASE}/fonts/bootstrap-icons.woff2"


def fetch(url: str, dest: Path) -> bytes:
    if dest.exists():
        return dest.read_bytes()
    dest.parent.mkdir(parents=True, exist_ok=True)
    print(f"  fetching {url}")
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    dest.write_bytes(data)
    return data


def used_icons(html: str) -> list[str]:
    """Icon names referenced in the markup.

    Matches class tokens only, so the word 'bi-' inside prose or a comment
    cannot invent a glyph that does not exist.
    """
    names: set[str] = set()
    for attr in re.findall(r'class="([^"]+)"', html):
        for tok in attr.split():
            if tok.startswith("bi-") and len(tok) > 3:
                names.add(tok[3:])
    return sorted(names)


def main() -> int:
    html = HTML.read_text(encoding="utf-8")
    wanted = used_icons(html)
    print(f"icons referenced in index.html: {len(wanted)}")

    raw_css = fetch(UP_CSS, CACHE / "bootstrap-icons.min.css").decode("utf-8")
    woff2 = fetch(UP_WOFF2, CACHE / "bootstrap-icons.woff2")
    print(f"  upstream css   {len(raw_css) / 1024:7.1f} KB")
    print(f"  upstream woff2 {len(woff2) / 1024:7.1f} KB")

    # map: icon-name -> codepoint, from the upstream ".bi-x::before{content:"\f123"}"
    pairs = dict(
        re.findall(r'\.bi-([a-z0-9-]+)::before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"', raw_css)
    )
    if not pairs:
        print("FAIL  could not parse icon codepoints from upstream CSS")
        return 1
    print(f"  upstream declares {len(pairs)} icons")

    missing = [n for n in wanted if n not in pairs]
    if missing:
        print(f"FAIL  these icons do not exist upstream (typo?): {missing}")
        return 1

    keep = {n: pairs[n] for n in wanted}

    # ---- subset the font to only the needed glyphs ----
    try:
        from fontTools import subset
        from fontTools.ttLib import TTFont
    except ImportError:
        print("FAIL  fonttools not installed -> pip install fonttools brotli")
        return 1

    unicodes = [int(cp, 16) for cp in keep.values()]
    font = TTFont(io.BytesIO(woff2))
    subsetter = subset.Subsetter(
        options=subset.Options(
            layout_features=[],
            notdef_outline=True,
            drop_tables=["GSUB", "GPOS", "GDEF", "morx", "kern"],
        )
    )
    subsetter.populate(unicodes=unicodes)
    subsetter.subset(font)

    FONT_DIR.mkdir(parents=True, exist_ok=True)
    out_font = FONT_DIR / "bi-subset.woff2"
    font.flavor = "woff2"
    font.save(out_font)
    saved = (len(woff2) - out_font.stat().st_size) / 1024
    print(
        f"  subset woff2   {out_font.stat().st_size / 1024:7.1f} KB "
        f"({len(unicodes)} glyphs, saved {saved:.1f} KB)"
    )

    # ---- emit the CSS ----
    lines = [
        "/* ============================================================",
        "   00. ICONS — self-hosted Bootstrap Icons subset",
        "   ------------------------------------------------------------",
        "   GENERATED by build-icons.py. Do not edit by hand.",
        "",
        f"   Contains only the {len(keep)} icons index.html actually uses, out of",
        f"   the {len(pairs)} upstream. This replaced a render-blocking",
        "   third-party stylesheet whose fetch time was measured driving",
        "   first paint (182 ms best / 1086 ms worst across runs).",
        "",
        "   font-display: block is deliberate for icon fonts: 'swap' would",
        "   paint a fallback glyph box first and then reflow, which on an",
        "   icon face means visible garbage characters.",
        "   ============================================================ */",
        "",
        "@font-face {",
        '  font-family: "bootstrap-icons";',
        "  font-display: block;",
        '  src: url("../fonts/bi-subset.woff2") format("woff2");',
        "}",
        "",
        ".bi::before,",
        '[class^="bi-"]::before,',
        '[class*=" bi-"]::before {',
        '  display: inline-block;',
        '  font-family: "bootstrap-icons" !important;',
        "  font-style: normal;",
        "  font-weight: normal !important;",
        "  font-variant: normal;",
        "  text-transform: none;",
        "  line-height: 1;",
        "  vertical-align: -0.125em;",
        "  -webkit-font-smoothing: antialiased;",
        "  -moz-osx-font-smoothing: grayscale;",
        "}",
        "",
    ]
    for name in sorted(keep):
        lines.append(f'.bi-{name}::before {{ content: "\\{keep[name]}"; }}')
    lines.append("")

    OUT_CSS.write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote {OUT_CSS.relative_to(ROOT)} ({OUT_CSS.stat().st_size / 1024:.1f} KB)")
    print("\nNext: python build-css.py  (00-icons.css is picked up automatically)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
